#dev application properties

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

spring.datasource.url=jdbc:h2:file:./data/riskdb
spring.datasource.driverClassName=org.h2.Driver
#username and password would not be stored here - just for demo
spring.datasource.username=sa
spring.datasource.password=
spring.flyway.locations=classpath:db/migration
spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate

#debugging
logging.level.org.flywaydb=DEBUG
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#username and password would not be stored here - just for demo
spring.security.user.name=admin
spring.security.user.password=password


#application values - improvements would be having external property config
risk.rule.evaluator.decline.threshold=70
risk.rule.evaluator.review.threshold=40
risk.rule.evaluator.timeout.value=3

amount.rule.high.risk.amount=1000
amount.rule.medium.risk.amount=500
amount.rule.high.risk.value=10
amount.rule.medium.risk.value=5

credit.score.high.risk.score.threshold=500
credit.score.medium.risk.score.threshold=650
credit.score.high.risk.value=50
credit.score.medium.risk.value=20
credit.score.cache.maximum-size=10000
credit.score.cache.expire-after-write-minutes=1000

buyer.merchant.rule.low.risk.value=0
buyer.merchant.rule.medium.risk.value=50

risk.rule.executor.core.pool.size=4
risk.rule.executor.max.pool.size=8
risk.rule.executor.queue.capacity=50

ip.geo.location.api.endpoint=http://ip-api.com/json/
ip.geo.location.api.connect.timeout=1s
ip.geo.location.api.read.timeout=2s
